const express = require('express')
const compression = require('compression')
const ejs = require('ejs')
const package = require('./package.json')

// Express
const app = express()
app.set('views', './dist')
app.set('view engine', 'html')
app.engine('html', ejs.renderFile)

// Send gzip version of Javascript files (generated by webpack)
app.get('*.js', (req, res, next) => {
  req.url = req.url + '.gz'
  res.set('Content-Encoding', 'gzip')
  next()
})

// Serve static files from `dist` directory (except `index.html`, which is rendered with params)
app.use(express.static('dist', {index: false}))

// SPA sends the same index.html page for all requests
app.get('*', (request, response) => {
  response.render('index', {
    apiURL: process.env.SERVER_URL,
    apiID: process.env.APP_ID
  })
})

app.listen(process.env.PORT || 3000, () => {
  console.log(`${package.name} (${package.version}) listening on port ${process.env.PORT || 3000}`)
})
